language: java
jdk:
    oraclejdk8
cache:
    directories:
       - '$HOME/.m2/repository'

before_install:
   - source deploy/before_install.sh

after_success:
   - source deploy/after_success.sh

after_failure:
   - source deploy/after_failure.sh