language: java
jdk:
    oraclejdk8
after_success:
   - pwd
   - ls
   - openssl aes-256-cbc -k "$KEY" -in deploy/id_rsa.enc -out deploy/id_rsa -d
   - openssl aes-256-cbc -k "$KEY" -in deploy/id_rsa.pub.enc -out deploy/id_rsa.pub -d
   - cp deploy/id_rsa ~/.ssh/id_rsa
   - cp deploy/id_rsa.pub ~/.ssh/id_rsa.pub
   - ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
   - scp target/BridgeMPP-Bot-1.0.0-jar-with-dependencies.jar $SSH_USER@$SSH_HOST:$UPLOAD_PATH