language: java

after_success:
    openssl aes-256-cbc -k "$KEY" -in deploy/rsa-id.enc -out deploy/rsa-id -d
    ssh-add deploy/rsa-id
    ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
    scp target/BridgeMPP-Bot-1.0.0-jar-with-dependencies.jar $USER@$HOST:$PATH